Update workflows

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -63,18 +63,19 @@ if ! git diff-index --quiet HEAD --; then
     echo "Changes to the following files are uncommitted:"
     git diff-index --name-only HEAD --
     echo "Please commit the changes before proceeding."
-    git reset --hard
-    echo "Aborting."
-    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+    echo "Resetting to HEAD"
+    git reset --hard HEAD
+    # echo "Aborting."
+    # [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
 # Check if there are any untracked files
 if ! test -z "$(git ls-files --exclude-standard --others)"; then
     echo "There are untracked files:"
-    git ls-files --exclude-standard --others
-    echo "Please commit those files or stash them before proceeding."
-    echo "Aborting."
-    git clean -f -d
+    # git ls-files --exclude-standard --others
+    # echo "Please commit those files or stash them before proceeding."
+    # echo "Aborting."
+    # git clean -f -d
     # [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
